"""create account table

Revision ID: 74b7f5bc4646
Revises: 5aef99ad21e0
Create Date: 2023-10-09 15:15:07.624102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74b7f5bc4646'
down_revision: Union[str, None] = '5aef99ad21e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=225), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(length=225), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('password')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    op.create_table('countries',
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('country_name', sa.String(), nullable=False),
    sa.Column('capital', sa.String(), nullable=True),
    sa.Column('official_lang', sa.String(), nullable=True),
    sa.Column('area', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('user_creator_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_creator_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('country_id')
    )
    op.create_index(op.f('ix_countries_country_id'), 'countries', ['country_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_countries_country_id'), table_name='countries')
    op.drop_table('countries')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
